CREATE TABLE IF NOT EXISTS CIRCLES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME CHAR(30) NOT NULL,
    CREATED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP
);